config/routes.rb
Rails.application.routes.draw do
  root                           'main#index'
  get 'help'                  => 'main#help'
  get 'signup'                => 'users#new'
  get 'login'                 => 'sessions#new'
  post 'login'                => 'sessions#create'
  delete 'logout'             => 'sessions#destroy'
  #get 'competitions'          => 'competitions#index'
  g#et '/competitions/(:id)'   => 'competitions#select_photos'
  #get '/info/(:id)'           => 'competitions#show_info'
  #get '/results/(:id)'        => 'competitions#results'

  resources :users
  resources :themes #обеспечивает автоматический вызов всех методов REST
  resources :images
  resources :values

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/theme.rb
class Theme < ApplicationRecord
  #belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, :allow_destroy => true #добавляет вложенные атрибуты
  default_scope -> { order(created_at: :desc)} #задает порядок показа альбомов
  #validates :user_id, presence: true #проверка user_id в album
  validates :album_name, presence: true, length: {maximum: 100}
  validates :album_description, presence: true, length: {maximum: 200}

end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  # GET /themes
  # GET /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: 'Theme was successfully created.' }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to @theme, notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to themes_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theme_params
      params.require(:theme).permit(:name, :qty_items)
    end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/_form.html.slim
= form_for @theme do |f|
  - if @theme.errors.any?
    #error_explanation
      h2 = "#{pluralize(@theme.errors.count, "error")} prohibited this theme from being saved:"
      ul
        - @theme.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :qty_items
    = f.number_field :qty_items
  .actions = f.submit

app/views/themes/edit.html.slim
h1 Editing theme

== render 'form'

= link_to 'Show', @theme
'|
= link_to 'Back', themes_path

app/views/themes/index.html.slim
h1 Listing themes

table
  thead
    tr
      th Name
      th Qty items
      th
      th
      th

  tbody
    - @themes.each do |theme|
      tr
        td = theme.name
        td = theme.qty_items
        td = link_to 'Show', theme
        td = link_to 'Edit', edit_theme_path(theme)
        td = link_to 'Destroy', theme, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Theme', new_theme_path

app/views/themes/new.html.slim
h1 New theme

== render 'form'

= link_to 'Back', themes_path

app/views/themes/show.html.slim
p#notice = notice

p
  strong Name:
  = @theme.name
p
  strong Qty items:
  = @theme.qty_items

= link_to 'Edit', edit_theme_path(@theme)
'|
= link_to 'Back', themes_path