config/routes.rb
Rails.application.routes.draw do
  root                           'main#index'
  get 'help'                  => 'main#help'
  get 'signup'                => 'users#new'
  get 'login'                 => 'sessions#new'
  post 'login'                => 'sessions#create'
  delete 'logout'             => 'sessions#destroy'
  #get 'competitions'          => 'competitions#index'
  g#et '/competitions/(:id)'   => 'competitions#select_photos'
  #get '/info/(:id)'           => 'competitions#show_info'
  #get '/results/(:id)'        => 'competitions#results'

  resources :users
  resources :themes #обеспечивает автоматический вызов всех методов REST
  resources :images
  resources :values

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :theme
  has_many :values
  validates_presence_of :name, :file
  validate :file_size

  private
  #проверка размера изображения
  def file_size
    if file.size > 3.megabytes
      errors.add(:file, 'должен быть меньше 3Мб')
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to root_url, notice: 'Фото добавлено.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to root_url, notice: 'Фото успешно обновлено.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Фото удалено.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:name, :file, :ave_value, :theme_id)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.slim
= form_for @image do |f|
  - if @image.errors.any?
    #error_explanation
      h2 = "#{pluralize(@image.errors.count, "error")} prohibited this image from being saved:"
      ul
        - @image.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :file
    = f.text_field :file
  .field
    = f.label :ave_value
    = f.text_field :ave_value
  .field
    = f.label :theme_id
    = f.number_field :theme_id
  .actions = f.submit

app/views/images/edit.html.slim
h1 Editing image

== render 'form'

= link_to 'Show', @image
'|
= link_to 'Back', images_path

app/views/images/index.html.slim
h1 Listing images

table
  thead
    tr
      th Name
      th File
      th Ave value
      th Theme
      th
      th
      th

  tbody
    - @images.each do |image|
      tr
        td = image.name
        td = image.file
        td = image.ave_value
        td = image.theme_id
        td = link_to 'Show', image
        td = link_to 'Edit', edit_image_path(image)
        td = link_to 'Destroy', image, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Image', new_image_path

app/views/images/new.html.slim
h1 New image

== render 'form'

= link_to 'Back', images_path

app/views/images/show.html.slim
p#notice = notice

p
  strong Name:
  = @image.name
p
  strong File:
  = @image.file
p
  strong Ave value:
  = @image.ave_value
p
  strong Theme:
  = @image.theme_id

= link_to 'Edit', edit_image_path(@image)
'|
= link_to 'Back', images_path